
[dev]
   command = "npm run dev"

[build]
  command = "npm run generate"
  publish = "dist"
  functions = "functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
